name: advisoryapp_assigments
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.2.3
  shared_preferences: ^2.2.2
  formz: ^0.7.0
  validations:
    path: packages/validations
  authentication_repository:
    path: packages/authentication_repository
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
