name: authentication_repository
description: A repository for managing user authentication domain.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.2
  equatable: ^2.0.5
  flutter_facebook_auth: '^3.5.0'
  shared_preferences_manager: 
    path: ../shared_preferences_manager
  dio: ^5.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.1.4
  build_runner: ^2.1.11