// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9D-xghQyW-gQ6TJ176jPfYPlffiDZaY',
    appId: '1:568064410438:web:23fce5a4fc6f69346b5b47',
    messagingSenderId: '568064410438',
    projectId: 'advisoryapp-80a38',
    authDomain: 'advisoryapp-80a38.firebaseapp.com',
    storageBucket: 'advisoryapp-80a38.appspot.com',
    measurementId: 'G-059TKXZV02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITWz06u1w9ohiiNHw7nSPaPLUuRv_W4c',
    appId: '1:568064410438:android:8bee585a85eeec7c6b5b47',
    messagingSenderId: '568064410438',
    projectId: 'advisoryapp-80a38',
    storageBucket: 'advisoryapp-80a38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnZvXjEJDekuKrTZRy0XydYJfnIss6P8',
    appId: '1:568064410438:ios:4ecfa743d47121b36b5b47',
    messagingSenderId: '568064410438',
    projectId: 'advisoryapp-80a38',
    storageBucket: 'advisoryapp-80a38.appspot.com',
    iosBundleId: 'com.example.advisoryappAssigments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKnZvXjEJDekuKrTZRy0XydYJfnIss6P8',
    appId: '1:568064410438:ios:4ecfa743d47121b36b5b47',
    messagingSenderId: '568064410438',
    projectId: 'advisoryapp-80a38',
    storageBucket: 'advisoryapp-80a38.appspot.com',
    iosBundleId: 'com.example.advisoryappAssigments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt9D-xghQyW-gQ6TJ176jPfYPlffiDZaY',
    appId: '1:568064410438:web:0274f06966c40fb86b5b47',
    messagingSenderId: '568064410438',
    projectId: 'advisoryapp-80a38',
    authDomain: 'advisoryapp-80a38.firebaseapp.com',
    storageBucket: 'advisoryapp-80a38.appspot.com',
    measurementId: 'G-NZBTTLNRS6',
  );
}
